# Generated by Django 3.2.5 on 2021-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcase',
            name='selected',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
