# Generated by Django 3.2.5 on 2021-08-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_stepuser_feedback'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='step',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='lessons.step'),
        ),
    ]
