# Generated by Django 3.2.5 on 2021-07-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_taskcase_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='step',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskcase',
            name='selected',
            field=models.BooleanField(null=True),
        ),
    ]
