# Generated by Django 3.2.5 on 2021-08-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20210730_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskCase',
        ),
    ]
