# Generated by Django 3.2.5 on 2021-08-04 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_delete_taskcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=1024)),
                ('is_required', models.BooleanField()),
                ('selected', models.BooleanField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='quizzes.task')),
            ],
        ),
    ]
