# Generated by Django 3.2.5 on 2021-08-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='unit',
            new_name='lesson',
        ),
    ]
