# Generated by Django 3.2.5 on 2021-08-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_rename_unit_step_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepuser',
            name='feedback',
            field=models.CharField(default='no feedback', max_length=1024),
        ),
    ]
