# Generated by Django 3.2.5 on 2021-08-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_stepuser_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepuser',
            name='score',
        ),
    ]
