# Generated by Django 3.2.5 on 2021-08-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_stepuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepuser',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
